### ISSUE TITLE
Downloaded zip is 0Kb and fails to open

### ISSUE THREAD

**Issue by rv816** [OHDSI/Athena#1]
Followed process as normal using  athena web interface. Sent an email with a link that redirected to the following:

[http://91.225.130.23/vocab_files/vocab_download_v5_%7B901B08F7-C207-AD9B-C922-1C33569173B8%7D.zip](http://91.225.130.23/vocab_files/vocab_download_v5_%7B901B08F7-C207-AD9B-C922-1C33569173B8%7D.zip) . 

The download completed (quickly), but  the resulting file failed to open (stuck in a zip <=> cpgz loop).

Tried with both Safari and Chrome. Using Mac OSX Mavericks.

**Comment by cgreich** [comment]
rv816: Will fix shortly. Try again.

**Comment by cgreich** [comment]
Fixed.
