### ISSUE TITLE
Unable to verify e-mail address when registering

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Athena#10]
The URL in the e-mail appears valid:
```
http://www.arachnenetwork.com/api/v1/user-management/activation/<deleted for privacy>?callbackUrl=http://athena.ohdsi.org/auth/login
```
but it automatically redirects to an invalid URL:
```
https://arachnenetwork.comapi/v1/user-management/activation/<deleted for privacy>?callbackUrl=http://athena.ohdsi.org/auth/login
```
This happens both in Chrome and Internet Explorer

**Comment by mpozhidaeva** [comment]
@schuemie - the related bug with #9 - please check again

**Comment by schuemie** [comment]
I'm not sure what you mean.

I can't register again because it says my e-mail address is already taken.

I can't authenticate my e-mail because of the problem mentioned at the top.

I can't log in because my account is not authenticated.

What should I do?

**Comment by mpozhidaeva** [comment]
I mean try to follow the link from email and check redirection please

**Comment by schuemie** [comment]
I've now tried the link on multiple devices, and it still redirects me to an invalid URL

**Comment by mpozhidaeva** [comment]
We understand current state and are working on a fix. I will inform next steps after fixing.
Sorry for waiting.
