### ISSUE TITLE
Error in Athena concept.csv

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#11]
In my concept.csv (downloaded yesterday) I see this line:

<img width="638" alt="screenshot 2017-11-22 17 45 24" src="https://user-images.githubusercontent.com/7252105/33139234-f7bea2dc-cfac-11e7-83e5-b5edafadc4da.png">

**Comment by mpozhidaeva** [comment]
Hello, will check

**Comment by dimshitc** [comment]
Hi, we checked this in SNOMED source tables, and the bug is in the source, so we don't know what is the actual name, and for now we don't touch this in our vocabulary, but we'll report to a NHS (this is UK SNOMED extension), and once they fix it, we update the vocabulary.

**Comment by PRijnbeek** [comment]
Sure, thanks!
