### ISSUE TITLE
Vocabularies now use datetime fields instead of date?

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#12]
In the downloaded Athena files all the date fields are now in datetime format. According to the CDM v5.2 specs (https://github.com/OHDSI/CommonDataModel/wiki/CONCEPT) and DDL this should be date fields. The effect is I cannot load the vocabs in the CDM!! 

concept_id	concept_name	domain_id	vocabulary_id	concept_class_id	standard_concept	concept_code	valid_start_date	valid_end_date	invalid_reason
42732169	Radical resection of bone tumor, proximal humerus; with autograft (includes obtaining graft)	Procedure	CPT4	CPT4		23221	1970-01-01 00:00:00.0	2010-04-03 00:00:00.0	D

**Comment by PRijnbeek** [comment]
If you need a quick fix you can run this under linux:

sed -i -- 's/ 00:00:00.0//g' DRUG_STRENGTH.csv
sed -i -- 's/ 00:00:00.0//g' CONCEPT.csv
sed -i -- 's/ 00:00:00.0//g' CONCEPT_RELATIONSHIP.csv

It will replace all occurrences in these files and saves the original files as .csv--

**Comment by dimshitc** [comment]
We are working on this and in the next release this suppose to be fixed.
I'll keep you posted

**Comment by dimshitc** [comment]
Fixed!
Feel free to download it from Athena
