### ISSUE TITLE
Put OHDSI Athena on https

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#132]
Could the team add a SSL certificate to Athena please. There are issues with using it internally in companies. Most importantly our Passwords can easily be hacked.

**Comment by acumarav** [comment]
Hello @PRijnbeek,
HTTPS is good change for sure, we will sort it out.
Just want to emphasize that Authentication happens through CAS App over HTTPS so passwords cannot be hacked.

**Comment by konstjar** [comment]
SSL was configured.

**Comment by lopsided** [comment]
There appear to be some SSL issues on Athena now. I've tried to register a new account but now the log in popup window won't load, showing a 500 server error and the following message:

```
Error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by konstjar** [comment]
It was related to SSL certificate update, should be fixed now.
