### ISSUE TITLE
Issue with missing CPT4 code

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#138]
700360		Procedure	CPT4	CPT4	S	87635	19700101	20991231	

was not processed and this results in a foreign key constraint error in the CDM.

Is the short term solution to add this one manually?

This is related to Covid some maybe not in UMLS:

https://athena.ohdsi.org/search-terms/terms?query=700360&page=1

**Comment by acumarav** [comment]
During the production operation activities, an old version of the CPT4.jar has been rewritten which cause this issue. Patched version with the latest concepts is restored now but bundles should be reassembled (archived-restored)  to include it in the pack.
Another option is to download only updated CPT4.jar from the Athena repository:
https://github.com/OHDSI/Athena/blob/develop/src/main/docker/cpt4.jar
