### ISSUE TITLE
Athena CPT.bat in Vocabulary Files Fails

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Athena#14]
Hello,

When I run the cpt bat downloaded with the vocabularies the update fails with 

Update failed. UMLS web-API crashed.

Exception in thread "main" java.lang.NoClassDefFoundError: com/opencsv/CSVParser
at org.odhsi.utils.cpt.Application.upsertCpt4Data(Application.java:59)
at org.odhsi.utils.cpt.Application.main(Application.java:46)
Caused by: java.lang.ClassNotFoundException: com.opencsv.CSVParser
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 2 more

Please see this post in usagi forum for more history: Question About Matching Concepts #36

**Comment by mpozhidaeva** [comment]
@anonymous34, hello - do I correctly undestand you downloaded vocabularies from Athena (http://athena.ohdsi.org/) and tried to run cpt.bat from unzipped _downloaded_ folder (with the _lib_ folder there)?

BR

**Comment by anonymous34** [comment]
Yes, I think it is causing the index build to fail too.  The failure of the bat script truncates all the data in the concept csv file.  Here is the error file.

The following is taken from the Error.txt file

*** Generic error information ***
Message: null
Time: Dec 13, 2017 12:17:49 PM
Processor type: amd64
Available processors: 8
Maximum available memory: 3,790,077,952 bytes
Used memory: 47,118,864 bytes
Java version: 1.8.0_152
Java vendor: Oracle Corporation
OS architecture: amd64
OS name: Windows 7
OS version: 6.1
OS patch level: Service Pack 1

*** Stack trace ***
org.ohdsi.usagi.indexBuilding.ReadAthenaFile$AthenaFileIterator.<init>(Unknown Source)
org.ohdsi.usagi.indexBuilding.ReadAthenaFile.iterator(Unknown Source)
org.ohdsi.usagi.indexBuilding.BerkeleyDbBuilder.loadConcepts(Unknown Source)
org.ohdsi.usagi.indexBuilding.BerkeleyDbBuilder.buildIndex(Unknown Source)
org.ohdsi.usagi.indexBuilding.IndexBuildCoordinator$BuildThread.run(Unknown Source)


*** Working folder contents ***
Directory of C:\OMOP Vocabularies

Usagi_v1.1.3.jar                                                      19,144,870                   07-11-2017 07:31:18
DOMAIN.csv                                                                 1,213                   13-12-2017 12:04:06
CONCEPT_CLASS.csv                                                         13,271                   13-12-2017 12:04:06
CONCEPT_CPT4.csv                                                         917,449                   13-12-2017 12:04:06
CONCEPT_ANCESTOR.csv                                               2,621,882,537                   13-12-2017 12:08:03
RELATIONSHIP.csv                                                          31,732                   13-12-2017 12:08:03
CONCEPT_SYNONYM.csv                                                  518,890,995                   13-12-2017 12:08:47
VOCABULARY.csv                                                             8,426                   13-12-2017 12:08:47
CONCEPT_RELATIONSHIP.csv                                           1,576,828,862                   13-12-2017 12:10:22
DRUG_STRENGTH.csv                                                    134,650,423                   13-12-2017 12:10:28
cpt.bat                                                                       30                   13-12-2017 12:10:28
cpt.sh                                                                        32                   13-12-2017 12:10:28
lib                                                                            0      <DIR>        13-12-2017 12:10:29
readme.txt                                                                   475                   13-12-2017 12:10:29
cpt4.jar                                                                 592,710                   13-12-2017 12:10:30
CONCEPT.csv                                                                    0                   13-12-2017 12:10:40
Usagi-1.1.3                                                                4,096      <DIR>        13-12-2017 12:17:15
vocabularyVersion.txt                                                         16                   13-12-2017 12:17:48
sleepyCat                                                                  4,096      <DIR>        13-12-2017 12:17:49
Error.txt                                                                      0                   13-12-2017 12:17:49

Available disc space: 168,947,081,216 bytes

**Comment by anonymous34** [comment]
Any updates on this?  Our team needs to do some analysis so we need to have the cpt4 vocabulary available.    Thank you.

**Comment by mpozhidaeva** [comment]
@anonymous34, sorry for delay - unfortunately the exception is not reproduced. Please check content of lib folder (opencsv-3.3.jar is there?)
Anyway I can advice you to try reimport vocabs and repeat cpt4 command.

BR

**Comment by anonymous34** [comment]
Yes that file is there.  While this forum will not let me post screenshots, here are the steps I took to reproduce the error.  Please let me know if I missed a step or executed incorrectly.  I have been extracting the files from the zip file each time I have troubleshooted.  Is the vocabulary I downloaded corrupted perhaps?  Notice has the entire concept file was wiped out after I issued the jar command.

1) **Extract the vocabulary files using unzip utility in Windows 7 OS 64 bit.  The results of the extract in the extracted directory **before** running the script.**
Name                                        Type                                 Size
CONCEPT                                Microsoft Excel CSV           676,024 kb
CONCEPT_ANCESTOR              Microsoft Excel CSV           2,560,433 kb
CONCEPT_CLASS                     Microsoft Excel CSV           13 kb
CONCEPT_CPT4                       Microsoft Excel CSV           896 kb
CONCEPT_RELATIONSHIP        Microsoft Excel CSV           1,539,872 kb
CONCEPT_SYNONYM              Microsoft Excel CSV            506,730 kb
DOMAIN                                  Microsoft Excel CSV            2 kb
DRUG_STRENGTH                    Microsoft Excel CSV            131,495 kb
RELATIONSHIP                         Microsoft Excel CSV            31 kb
VOCABULARY                          Microsoft Excel CSV            1 kb
cpt                                           Windows batch file             1 KB
cpt                                           SH File                               1 KB
lib                                             File folder
readme                                     Text Document                  1 KB
cpt4                                         Executable Jar File               579 KB

_Files inside library folder:_
Name                                        Type                                 Size
commons-lang3-3.4                  Executable Jar File              425 KB
opencsv-3.3                               Executable Jar File              31 KB

2) **Run script in command prompt as instructed and view output steps**
a) Navigate to directory where script resides
b) Run the following in the command prompt as instructed in the readme file
     `java -jar cpt4.jar 5 `- Running this command produces this output: 
     `Update failed. UMLS web-API crashed.`
     
**3) View the file properties in the extracted directory. Notice the concept file is now 0 kb.  So the entire file was wiped out after running the command above.

_CONCEPT                                Microsoft Excel CSV           0 kb_
CONCEPT_ANCESTOR              Microsoft Excel CSV           2,560,433 kb
CONCEPT_CLASS                     Microsoft Excel CSV           13 kb
CONCEPT_CPT4                       Microsoft Excel CSV           896 kb
CONCEPT_RELATIONSHIP        Microsoft Excel CSV           1,539,872 kb
CONCEPT_SYNONYM              Microsoft Excel CSV            506,730 kb
DOMAIN                                  Microsoft Excel CSV            2 kb
DRUG_STRENGTH                    Microsoft Excel CSV            131,495 kb
RELATIONSHIP                         Microsoft Excel CSV            31 kb
VOCABULARY                          Microsoft Excel CSV            2 kb
cpt                                           Windows batch file             1 KB
cpt                                           SH File                               1 KB
lib                                             File folder
readme                                     Text Document                  1 KB
cpt4                                         Executable Jar File               579 KB

**Comment by mpozhidaeva** [comment]
Hello, yes - your steps are right. What vocabulary set did you download?What java version do your use?
Perhaps security protection closes access to the external service (UMLS API). Do you have opportunity to check behavior cpt4 in another computer (without the security constraints)?

BR

**Comment by anonymous34** [comment]
I downloaded from Athena website.  It is vocabulary_download_v5_{a0ab0d53-ffac-40ee-aff4-f51e1a515ea3}_1513106161850.  I am using Version 8 update 152 build 1.8.0_152-b16 on Windows 7.  I will see if I can try on another computer and get back to you.

**Comment by anonymous34** [comment]
So I tried on my home pc.  It has Java version 8 update 161 build 1.8.0-161-b12.  Now I got further than on my work pc os I think you are right about it being a security issue.  However, I got another error here:  Do you know where I should be setting the heap space in java or what the heap space parameter should be to complete the cpt4.bat script process?  See error below:

java -jar cpt4.jar 5
 Updated CPT4 records: 15446, records to update: 0
 Writing updated data to CONCEPT.csvException in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at com.opencsv.CSVWriter.writeNext(CSVWriter.java:254)
        at com.opencsv.CSVWriter.writeNext(CSVWriter.java:273)
        at org.odhsi.utils.cpt.Application.writeUniqueConceptRecord(Application.java:153)
        at org.odhsi.utils.cpt.Application.upsertCpt4Data(Application.java:116)
        at org.odhsi.utils.cpt.Application.main(Application.java:46)

**Comment by mpozhidaeva** [comment]
It is known issue:( 
I will try to reproduce your error and will inform your about solution.

As a hotfix you can try to run jar command with "max heap size" parameter: java -Xmx1024M -jar cpt4.jar 5 (please unzip downloaded folder again for unspoilt CONCEPT.csv). 
For checking default heap size please execute command `java -XX:+PrintFlagsFinal -version | findstr HeapSize` (for windows) or java `-XX:+PrintFlagsFinal -version | grep HeapSize` (for Unix/Linux). Please sent me console output after running this command.

Also you can try to download smaller vocabulary set (if it is not critically) and try again.

BR

**Comment by schuemie** [comment]
@mpozhidaeva, maybe this helps with the heap problem: you can set the heap size at runtime using a simple hack, like [here in Usagi](https://github.com/OHDSI/Usagi/blob/master/src/org/ohdsi/usagi/Launcher.java)

**Comment by mpozhidaeva** [comment]
@schuemie - thank you very much!
It is not "honest" solution - but as hotfix is ok

BR

**Comment by anonymous34** [comment]
Thank you guys.  The script says it loaded successfully but we now have a bigger issue.  We need to load the concept csv files into our tables in Oracle using Informatica ETL tool.  The issue is the files have no delimiter between the column data.  Delimiters are needed to load the data.

Here are a few examples of what the data looks like.  While these files can be read by Usagi, 

concept_id	concept_name	                                      domain_id	    vocabulary_id	concept_class_id	
2722219	        Laparoscopy, surgical; splenectomy.    Procedure      CPT4                    CPT4

**Comment by mpozhidaeva** [comment]
@anonymous34, actually the files have tab-separated values - could you set '\t' as delimiter in the Informatica ETL Tool?

**Comment by olga-ganina** [comment]
Relates #89

**Comment by acumarav** [comment]
closing as #89  was released
