### ISSUE TITLE
CPT updates to CONCEPT.csv break line terminators on Windows

### ISSUE THREAD

**Issue by cg3y** [OHDSI/Athena#140]
The CONCEPT.CSV file that is downloaded contains line feeds as record terminators. On Windows when the CPT download is run against the UMLS it adds the CPT concepts to this file with CrLf terminators. This makes the file inconsistent with the CPT records having different terminators (Carriage Return + Line Feed) than the rest of the file (Line Feeds only). This breaks the ability to import/load the data.

**Comment by acumarav** [comment]
During the production operation activities, an old version of the CPT4.jar has been rewritten which cause this issue. The latest version is restored now but bundles should be reassembled (archived-restored) to include it in the pack.
Another option is to download only updated CPT4.jar from the Athena repository:
https://github.com/OHDSI/Athena/blob/develop/src/main/docker/cpt4.jar
