### ISSUE TITLE
Password recovery does not work for emails in upper case

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Athena#143]
e.g. Kirill.Sadomtsev@odysseusinc.com

steps:
1)Try to recover password with an email which contains symbols in upper case

Expected:
password recovered

Actual:
password recovery does not work

**Comment by acumarav** [comment]
Athena uses Arachne for the "reset password" so the problem should be fixed there. I have created OHDSI/ArachneCentralAPI#677 for this change. Unfortunately Arachne login currently is case sensitive so we cannot patch it by lowercasing on the Athena side.
