### ISSUE TITLE
reset password question

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#15]
It is not very intuitive that if you reset the password and click on the link you are not forwarded to a form to really reset you password.

Actually, it is unclear to me where i can do that now I am automatically logged in?

**Comment by mpozhidaeva** [comment]
Hello @PRijnbeek,
After requesting of password reset you should get an email with the link for redirecting to a new password form. Next step after entering new password and clicking "request" is login in Athena (button "click here to login").

If you are already logged in your name will be in the upper right corner of the screen. 

Please specify your steps if this information is not enough.
BR
