### ISSUE TITLE
Does this repo contain the latest Athena source code?

### ISSUE THREAD

**Issue by CarthageKing** [OHDSI/Athena#17]
Hi,

Latest commit against this repo was Jun 28, 2016 (as per the posting of this question).

However, when clicking the question mark icon at the upper right portion of the https://athena.odysseusinc.com/search-terms/terms page, the version "Version 1.5.0.28.2017-12-21 10:24:24 EST" is displayed.

So it looks like there's about a 1.5 year difference between the GitHub commit date and the version number date.

Is the version number displayed on the page just a build version number or does it correspond to an actual release in this GitHub repo?

Best Regards,

**Comment by gklebanov** [comment]
Ah - you are right, there was a major Athena revamp done. At this moment, what you see in GitHub is version 1, we will be committing version 2 shortly, actually just debated on the best way to do it. Stayed tuned, the latest code is coming..

**Comment by CarthageKing** [comment]
Thanks for the fast response! :) Cool, will wait for the code drop then.
