### ISSUE TITLE
Athena vocabs list not available

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#175]
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/7252105/86240847-323a5080-bba2-11ea-8d3f-9aa6ede79eaa.png">

I do not seem to get the list of vocabs today? Is there an issue, maintenance ongoing?

**Comment by PRijnbeek** [comment]
Tried multiple times but now seems to work again maybe something to keep an eye on.

**Comment by acumarav** [comment]
hello @PRijnbeek, we had new vocabularies release today which cause some downtime. It was 4 hours ago.

**Comment by PRijnbeek** [comment]
Thanks that is good to know that this will make it unavailable.

**Comment by PRijnbeek** [comment]
actually i still get errors

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/7252105/86244939-02db1200-bba9-11ea-8e05-814040006793.png">
