### ISSUE TITLE
registration process not working

### ISSUE THREAD

**Issue by XcrigX** [OHDSI/Athena#18]
I have tried to register at http://athena.ohdsi.org/auth/register  several times. 

Each time when clicking the "Register" button, the button text changes to "REGISTERING..." and nothing else happens. No email is sent, the page does not redirect. Attempting to logon with the credentials used does not work, etc. 
I have tried two different browsers and on multiple days. Different email addresses, different passwords, etc. 
Is the registration process broken currently?

**Comment by gklebanov** [comment]
Dear Sam. Sorry you are having a trouble with registering. I am tagging our ATHENA support team, someone will contact you shortly

@pavgra

**Comment by pavgra** [comment]
@XcrigX, we will start working on the issue shortly and will let you know results asap

**Comment by pavgra** [comment]
@XcrigX, could you give it one more try? The issue should be resolved now

**Comment by XcrigX** [comment]
Working now. Thanks!
