### ISSUE TITLE
Display version of OMOP vocabulary

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Athena#19]
The new Athena tool to search the vocabulary is great. It would be nice to have an easy way to find out which version of the vocabulary (i.e., what release date) is being used.

**Comment by mpozhidaeva** [comment]
@cukarthik - thank you for the feedback! We inform you about the updates after implementation.
BR

**Comment by swoodVMD** [comment]
The updated vocabularies are very helpful, thank you. Is it possible to also include related 'concept' attributes such as Concept Relationship in the new version releases?

**Comment by dimshitc** [comment]
@swoodVMD 
to get the concept relationships you need to click on "Related concepts"
http://athena.ohdsi.org/search-terms/terms/36717156/table?fullscreen=false&levels=10&standardsOnly=false&zoomLevel=4
![image](https://user-images.githubusercontent.com/8568959/38602188-b38560ea-3d72-11e8-9c10-1ba94f53be83.png)

@cukarthik , there's the "latest update" field
http://athena.ohdsi.org/vocabulary/list
corresponding to the vocabulary release date.

**Comment by dimshitc** [comment]
go here
http://athena.ohdsi.org/vocabulary/list
register
then you see the list of the vocabularies
then download (there are check-boxes allowing you to choose which vocabularies would be downloaded)

**Comment by olga-ganina** [comment]
Fixed by #13
