### ISSUE TITLE
Error in building docker image

### ISSUE THREAD

**Issue by gkovaig** [OHDSI/Athena#192]
Environment: Ubuntu 20.04, Docker version 19.03.12

Steps to recreate:
1. git clone git clone https://github.com/OHDSI/Athena.git
2. cd Athena/src/main/docker
3. sudo docker build -f Dockerfile .
Fails on Step 6/14

Step 5/14 : VOLUME /tmp
 ---> Running in 4f303cf33d58
Removing intermediate container 4f303cf33d58
 ---> fcd728183590
Step 6/14 : COPY athena.jar /athena.jar
COPY failed: stat /var/lib/docker/tmp/docker-builder509829320/athena.jar: no such file or directory

**Comment by acumarav** [comment]
Hello @gkovaig, as per error message there is no  athena.jar file. There is maven build which includes docker build as a step
You can run this command to build with test profile: 
```mvn clean package deploy -Ptest  -DskipTests
Or if you want to build just a athena.jar then use:
```mvn clean package deploy -Ptest  -DskipTests -DskipDocker
