### ISSUE TITLE
List the OMOP release version in Athena

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Athena#199]
Is there an easy way to see what version of the vocabulary is in Athena? I usually query the vocabulary table for vocabulary_id='None' in SQL. I want to compare how far off my vocabulary version is to Athena. Thanks.

**Comment by acumarav** [comment]
Hello @cukarthik,

It is shown in the about window (Question mark on the right):
![image](https://user-images.githubusercontent.com/7705583/97674806-6c532a80-1a8e-11eb-862b-c1e1d8b16f76.png)
