### ISSUE TITLE
cpt4.jar

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Athena#2]
It seems CPT4 reconstitution doesn’t work correctly. 

Java program completes with message “Records imported: 14202. CPT successfully updated.” But the file is not written completely, it ends in the middle of line: 

![bug](https://cloud.githubusercontent.com/assets/6305439/8816655/fd984746-2ff7-11e5-9ed0-ef85c151d5f2.png)

So I had to delete this broken line and the number of CPT4 concepts imported is 11048 (v4.5) and 11057 (v5).

**Comment by cgreich** [comment]
Yes, we have this bug in the making. Gleb will soon release a debugging version, which will write out a whole lot of diagnostics to figure out what's going on. Hang on, please.

**Comment by cgreich** [comment]
@ericaVoss:

We added full error reporting to the CPT4 utility. Can you be so kind and download and run it again? And post the nagging it will produce.

**Comment by ericaVoss** [comment]
@cgreich  on it . . .

**Comment by GlebMalikov** [comment]
Issue is fixed, new version is available for download.

**Comment by ericaVoss** [comment]
We tested this for `OMOP_Vocabulary_v4.5_20150717` and it works.  We will also try `v5.0`.

**Comment by ericaVoss** [comment]
Things look good on our side, closing issue.

We also redownloaded based on this comment:
http://forums.ohdsi.org/t/cdm-4-5-issue-vocabulary-id-12-is-missing/718
