### ISSUE TITLE
Download email contains the name of the download

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Athena#20]
It would be nice if the download email contains the name we set for the download. Sometimes, I download two different packaged OMOP vocabularies - one with all the vocabularies and another with a much smaller subset. When I look at my email, it would be nice to know which packaged vocabulary the email is referring to.

**Comment by vojtechhuser** [comment]
+1

**Comment by acumarav** [comment]
PR: https://github.com/OHDSI/Athena/pull/110

**Comment by acumarav** [comment]
Example of the email body:
![image](https://user-images.githubusercontent.com/7705583/76299021-a5018200-62ba-11ea-9505-2f65aa9c49ab.png)
