### ISSUE TITLE
Validity dates for Concepts

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Athena#21]
Currently, we are not displaying valid_start_date and valid_end_date. Why not?

**Comment by pavgra** [comment]
@cgreich, we are not able to display the dates in table due to space reasons (even on wide screen there is not enough space for two additional columns). Inside of concepts, we will add display of the dates.

**Comment by mpozhidaeva** [comment]
@cgreich - the issue is implemented and deployed (release 1.7)
