### ISSUE TITLE
Restoring Downloads

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Athena#22]
If I restore a download, does it create a new download with most recent OMOP vocabulary for the selected vocabularies or does it send us the OMOP vocabulary that was initially created at the time it was first downloaded? Thanks.

**Comment by mpozhidaeva** [comment]
@cukarthik - hello, after restoration you get the current version of vocabularies.
BR

**Comment by cukarthik** [comment]
Great! Thanks.
