### ISSUE TITLE
Where can I download the cdmv5 vocabulary?

### ISSUE THREAD

**Issue by stevensantos2** [OHDSI/Athena#223]
All I can find in this repo are sql scripts on populating the tables. I was wondering if you can tell me where and how I can download cdmv5. Thank you.

**Comment by adikulkarni11** [comment]
I have the same question.

**Comment by acumarav** [comment]
@stevensantos2 and @adikulkarni11 , please register and login - after that you will see Download menu:
![image](https://user-images.githubusercontent.com/7705583/105815951-f0488000-5fb3-11eb-8e1d-c65153a3443d.png)
