### ISSUE TITLE
Can't download vocabularies. Java exception.

### ISSUE THREAD

**Issue by asivura** [OHDSI/Athena#252]
account: asivura@icloud.com
org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement

![image](https://user-images.githubusercontent.com/2479905/118197426-cd779580-b403-11eb-95d8-7ee7ad6139e3.png)

**Comment by asivura** [comment]
I have another issue now: 
![image](https://user-images.githubusercontent.com/2479905/118219235-ebf28680-b42d-11eb-807d-c70ae47e4af3.png)

**Comment by konstjar** [comment]
Please try request download again. The issue was resolved.

**Comment by asivura** [comment]
Thanks @konstjar . It works now.
