### ISSUE TITLE
Can't register to Athena

### ISSUE THREAD

**Issue by ods967** [OHDSI/Athena#253]
![Screenshot from 2021-05-14 13-11-51](https://user-images.githubusercontent.com/31992615/118256291-040de880-b4b6-11eb-8906-a3ddaabc9cef.png)
When open https://athena.ohdsi.org/auth/register 
https://athena.ohdsi.org/api/v1/users/professional-types
https://athena.ohdsi.org/api/v1/users/countries?query=&limit=10
https://athena.ohdsi.org/api/v1/users/provinces?query=&countryId=US&limit=10
return errorCode 4

**Comment by konstjar** [comment]
Thank you for reporting, the issue was resolved. Please try to register again.
