### ISSUE TITLE
Download of OSM data is not valid CSV

### ISSUE THREAD

**Issue by guneemwelloeux** [OHDSI/Athena#255]
Some rows in the OSM Vocabulary are not valid CSV.

Instead of single quote characters, a double quote is used, which is the separator for the CSV format of the download. This creates issues when trying to import to a database, like Postgres.

Example: Concept   `42075957    Rocky Boy"s Agency  Geography   OSM 8th level   S   142381  19700101    20991231`

If the vocabulary actually uses a double quote as an apostrophe (which I doubt), then the value should be escaped with double quotes, and the double quote should also be escaped, as follows.
`  42075957    "Rocky Boy""s Agency"  Geography   OSM 8th level   S   142381  19700101    20991231`

Other example in another vocabulary: `38003565    Payer enrollment status "Deceased"  Type Concept    Condition Type  Death Type      OMOP4822057 19700101    20991231`

**Comment by mik-ohdsi** [comment]
hi @guneemwelloeux , 
this might be more a Vocabulary building issue than an Athena issue. We will review that against the OSM creation process.
Does this cause any real trouble or is this issue rather a cosmetic one?
Your example shows what you perceive as a valid entry, right?
Cheers - Mik

**Comment by thisismexp** [comment]
Just recognized that OSM cannot be found any more on the download site.

**Comment by mik-ohdsi** [comment]
@thisismexp - There is a different reason for that: OSM currently is deemed indispensable and you get it with every download (it doesn't show up on the list, as you would not be able to deselect it anyway). There is another thread that discusses this: #278
To get back to the original post: this particular problem can and should be overcome by appropriate quoting adjustment on csv import (and to be honest, there is also a discussion saying that the csv files are actually rather tsv files... true...)
Check out the quoting in the historic vocab import instructions (e.g. here for [PostGreS](https://github.com/OHDSI/CommonDataModel/tree/v5.3.1/PostgreSQL/VocabImport)) or find inspiration in the ETL-Synthea Vocab [Import logic](https://github.com/OHDSI/ETL-Synthea/blob/master/R/LoadVocabFromCsv.r).

**Comment by thisismexp** [comment]
@mik-ohdsi thanks for your fast reply, and sry for hijacking this thread

**Comment by mik-ohdsi** [comment]
@guneemwelloeux - closing this issue! bottom line: we do not use quoting when packaging the vocabulary content and the quotes found in the file are to be kept as part of the field content... To turn off quote processing in PostGreS, you can [indicate a character](https://stackoverflow.com/questions/20402696/is-it-possible-to-turn-off-quote-processing-in-the-postgres-copy-command-with-cs) that definitely does not exist in the entire file.
