### ISSUE TITLE
Cannot Download any Vocabularies

### ISSUE THREAD

**Issue by brooklyOPC** [OHDSI/Athena#260]
I have tried 

- logging out and logging back in
- refreshing the page
- Empty cache and hard reload
- closing the page and re-navigating
- with and without the "Notify me about changes" option selected
- selecting only one vocabulary set
- selecting multiple vocabulary sets

No matter what I get the same error:
![image](https://user-images.githubusercontent.com/52915138/134539790-1799bcbb-064d-41e4-bff3-4714b4dad4ff.png)

I don't know if it's related, but there are also multiple vocabularies that don't have a check box next to them at all, and subsequently cannot be clicked. I didn't try to download these at all.
![image](https://user-images.githubusercontent.com/52915138/134539923-66baf77d-4a16-4f11-83b1-a09b367644ba.png)

**Comment by konstjar** [comment]
It was resolved. Please try to download again.
