### ISSUE TITLE
Proxy error on login

### ISSUE THREAD

**Issue by lyle0921** [OHDSI/Athena#261]
When trying to log in to my (new) account I receive a Proxy Error. This has occurred when trying to log in from multiple networks.
See attached for error message.

![Athena Log in Proxy Error](https://user-images.githubusercontent.com/91154096/134689732-da27586f-776e-410d-9052-91f29c7534ec.PNG)
e

**Comment by konstjar** [comment]
Thank you for reporting. This issue was resolved.
