### ISSUE TITLE
Vocabulary bundle download error

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Athena#269]
Greetings,

I am trying to download a latest version of my vocabulary bundle and I get the following error when I click on the download button:

org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement

I have tried with different subsets of the vocabulary with the same results.

Thanks!

**Comment by hamedn** [comment]
Hi,

I am running into the same issue.

**Comment by konstjar** [comment]
Thank you for reporting the issue. It was resolved.
