### ISSUE TITLE
cpt4.jar error (and suggested workaround)

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/Athena#27]
I went to run the cpt4.jar command that comes with the vocabulary downloads and I got the following error:

```
> java -jar cpt4.jar 5
Error: Unable to initialize main class org.odhsi.utils.cpt.Application
Caused by: java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException
```

I'm running a newer version of Java:

```
> java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

Looks like Java 9 and up might not include the javax.xml.ws module?  I don't know the right terminology as I'm not a Java guy.

Some quick Googling showed that I could fix the error by running the command thusly:

```
> java --add-modules=java.xml.ws -jar cpt4.jar 5
 Updated CPT4 records: 10542, records to update: 4904
```

We probably need to update the cpt.sh and cpt.bat files to incorporate this fix?

**Comment by rsjaffe** [comment]
this workaround fixed the issue for me too.

**Comment by olga-ganina** [comment]
Support of Java till version 13th is available on production
