### ISSUE TITLE
Can't download vocabularies. Java exception. 

### ISSUE THREAD

**Issue by MayMAAhmed** [OHDSI/Athena#273]
I'm getting an error to download an Athena vocabulary: 
![image](https://user-images.githubusercontent.com/22137134/155867881-e12fd724-eb3c-4571-b439-66da530fb262.png)

Please advise. 
Thanks,

**Comment by 20kpk** [comment]
I got the same issue when downloading the Multum vocabulary. 

Thanks.

**Comment by konstjar** [comment]
It was resolved

**Comment by MandersMRDM** [comment]
@konstjar for me this issue seems to occur again consistently.

**Comment by MandersMRDM** [comment]
> @konstjar for me this issue seems to occur again consistently.

And seems to be fixed again.
