### ISSUE TITLE
Cannot Download Vocabularies

### ISSUE THREAD

**Issue by choffer1120** [OHDSI/Athena#275]
Hi there, having the same issue as other issue's like #272 and #269 where trying to download vocabularies returns an error of:

`org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement`

Not sure if there is any fix we can do on our end, but let me know if so?

**Comment by liaoxiaolan** [comment]
I met the same trouble and I can not handle it.

**Comment by pazampog** [comment]
Same problem for me...I tried several time!

**Comment by josh-porter** [comment]
I'm having the same issue. I've been trying since yesterday afternoon.

**Comment by konstjar** [comment]
Thank you for reporting. It was resolved
