### ISSUE TITLE
Pallas emails are often rejected

### ISSUE THREAD

**Issue by mik-ohdsi** [OHDSI/Athena#279]
The Athena mailing logic uses the pallas@ohdsi.org mail address as sender. However, the emails are being sent through google. Many receiving email servers mark those emails as spam and reject them ("Sender rejected because SPF check failed!"). As a result, the account holders do not receive emails with a download link. Similarly, the emails notifying of a vocabulary update are rejected.
Please adjust the mailing logic by either using the pallas@ohdsi.org account for sending or by sending from a proper google account.

**Comment by mik-ohdsi** [comment]
this is connected to issue #271

**Comment by konstjar** [comment]
Probably it was resolved by changes in configuration

**Comment by mik-ohdsi** [comment]
yes, now it seems to be resolved. Thanks for fixing!
