### ISSUE TITLE
"GenericJDBCException: could not execute statement" when trying to download vocabularies

### ISSUE THREAD

**Issue by SulevR** [OHDSI/Athena#284]
I'm trying to download the following vocabularies from Athena, but getting error "org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement" after pressing Download button.

Tried several times. First time, I also got an automatic email "Sorry, there was an error while saving the Standardized Vocabularies."

The name of the package: "uus katse 2"

Selected vocabularies:

- SNOMED
- LOINC
- RxNorm
- Gender
- Race (Race and Ethnicity Code Set)
- MedDRA
- ATC
- ICD10
- Ethnicity
- ICD10CM
- RxNorm Extension
- OMOP Extension (OHDSI)
- NCIt (NCI Thesaurus (National Cancer Institute))
- Cancer Modifier (Diagnostic Modifiers of Cancer (OMOP))
- HemOnc
- Episode Type

**Comment by AndyStevens98** [comment]
+1 this issue, I'm running into the same error no matter what vocabularies I choose

**Comment by davidcraft** [comment]
+1

**Comment by smartin-arch** [comment]
Same here. 
Was able to "restore" an older download, but it contained a single test vocabulary and was not what I need now.

**Comment by konstjar** [comment]
Thanks for sharing. It should be fixed now.

**Comment by SulevR** [comment]
Yes, confirmed - is fixed now.
