### ISSUE TITLE
Able to register, but unable to login

### ISSUE THREAD

**Issue by GratefulDave** [OHDSI/Athena#285]
I have registered for an account through the normal process and created a profile & password. I am trying to download the standardized vocabulary but am unable to log in.  I am getting the following error on the login page [here](https://cas.odysseusinc.com/cas/idp/profile/SAML2/POST/SSO/Callback.+?entityId=com%3Aodysseusinc%3Aathena%3Asp&SAMLRequest=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOkF1dGhuUmVxdWVzdCB4bWxuczpzYW1sMnA9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCIgQXNzZXJ0aW9uQ29uc3VtZXJTZXJ2aWNlVVJMPSJodHRwczovL2F0aGVuYS5vaGRzaS5vcmcvYXV0aC9jYWxsYmFjaz9jbGllbnRfbmFtZT1TQU1MMkNsaWVudCIgRGVzdGluYXRpb249Imh0dHBzOi8vY2FzLm9keXNzZXVzaW5jLmNvbS9jYXMvaWRwL3Byb2ZpbGUvU0FNTDIvUmVkaXJlY3QvU1NPIiBGb3JjZUF1dGhuPSJmYWxzZSIgSUQ9Il9ham02eHdpbnhtaGNpNGs4dmkzbmV2bmZpc2Rza2JranNmNHhxdWkiIElzUGFzc2l2ZT0iZmFsc2UiIElzc3VlSW5zdGFudD0iMjAyMi0wNy0wNVQxNTo1NDowMC41NzhaIiBQcm90b2NvbEJpbmRpbmc9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpiaW5kaW5nczpIVFRQLVBPU1QiIFByb3ZpZGVyTmFtZT0icGFjNGotc2FtbCIgVmVyc2lvbj0iMi4wIj48c2FtbDI6SXNzdWVyIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj5jb206b2R5c3NldXNpbmM6YXRoZW5hOnNwPC9zYW1sMjpJc3N1ZXI%2BPC9zYW1sMnA6QXV0aG5SZXF1ZXN0Pg%3D%3D&RelayState=https%3A%2F%2Fathena.ohdsi.org%2Fauth%2Fcallback%3Fclient_name%3DSAML2Client&ticket=ST-237-oH3hH7QyGtlhhbWv4Wpi-cas.odysseusinc.com%3A443):

```
CAS is unable to process this request: "500:Internal Server Error"
There was an error trying to complete your request. Please notify your support desk or try again.

Apereo is a non-profit open source software governance foundation. The CAS software is an Apereo sponsored project and is freely downloadable and usable by anyone. However, Apereo does not operate the systems of anyone using the software and in most cases doesn't even know who is using it or how to contact them unless they are an active part of the Apereo community.

If you are having problems logging in using CAS, you will need to contact the IT staff or Help Desk of your organization for assistance.

We wish we could be more directly helpful to you.
```
The error response is:
```
Error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

null
```

It is not clear who I can contact to make sure my account is active and can resolve this issue.

**Comment by CristianoFugazza** [comment]
+1, have the very same issue

**Comment by Tobias-Be** [comment]
Have the same issue aswell

**Comment by rpstgnyc** [comment]
same issue for me, please help!
