### ISSUE TITLE
"Remind Password" function does not work anymore

### ISSUE THREAD

**Issue by mik-ohdsi** [OHDSI/Athena#286]
The function to get one's Athena password sent to the registered email seems not to work anymore. Maybe this is related to issue #279, because the email send function needs to be adapted.

**Comment by konstjar** [comment]
I think it was resolved by using correct mail service. @mik-ohdsi can you please confirm it works for you now?

**Comment by mik-ohdsi** [comment]
it works, thanks for fixing!
