### ISSUE TITLE
Athena Slowness and Blank page results

### ISSUE THREAD

**Issue by ranatech08** [OHDSI/Athena#288]
Hi,

Since 8th July 2022. the Athena isn't performing as it was doing before. Till date i.e. 12th July 2022 (4PM Singapore time), the issue is same and is effecting our work.

Issue:
1. Searching by "keyword" is taking approx 25-30 secs to display the result. 
2. Post the result appear, click on any of the row
3. The detail page (latency of another 30-40 secs) from the previous step row takes you to a **blank page** with **no results**

Please let me know if I need to upload the **Performance Insights** (Google Chrome Dev tools) containing the **Processed Trace Data**, which might help you in your debug. Also, let me know if any other methods I need to use to share the same with you.

Thanks,
Rana

**Comment by konstjar** [comment]
2 indices were added on DB table

```
CREATE INDEX idx_download_bundle_id on download_item(download_bundle_id);
CREATE INDEX idx_vocabulary_id_v4 on download_item(vocabulary_id_v4);
```

It should be reflected in the code

**Comment by konstjar** [comment]
@ranatech08 Let me know if the issue was resolved for you

**Comment by ranatech08** [comment]
Hi @konstjar , @mik-ohdsi ,

Thank you so much for the help!! Athena seems to be back to normal latency and we didn't face any further high latency.

Appreciate the quick response and resolution. I'm closing this issue thread.

Thanks,
Rana
