### ISSUE TITLE
Registration problems

### ISSUE THREAD

**Issue by sbreiff** [OHDSI/Athena#293]
I tried to register so that I could download vocabularies, but the registration box doesn't load the options for Country or Professional type and I am unable to finish registration. Is there another way to register? I tried in Chrome as well as Firefox but same problems in both browsers.

**Comment by emmaleof** [comment]
I have had the same issues today as well and have not been able to register. I have tried Chrome, Firefox, Edge, and IE (PC computer). Is there another way to register? Thanks.

**Comment by konstjar** [comment]
Please try again. There were technical issues on application side.

**Comment by emmaleof** [comment]
Thanks! I was able to register. Vocabs are currently pending download.

**Comment by sbreiff** [comment]
Same. Thanks.
