### ISSUE TITLE
Hibernate Exception Error upon trying to download Vocabluries

### ISSUE THREAD

**Issue by Yusuf023** [OHDSI/Athena#296]
Hi, 

I'm getting the following error upon trying to download vocabluries:
https://athena.ohdsi.org/vocabulary/list
`org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement`

Please let me know if I'm missing something

![image](https://user-images.githubusercontent.com/32506959/181696294-e5292717-21d8-41a4-8b99-d7531df51b70.png)

**Comment by konstjar** [comment]
Thank you for reporting. The problem was resolved.
