### ISSUE TITLE
 Vocabulary cannot be downloaded, it is pending, and it does not come through e-mail

### ISSUE THREAD

**Issue by abbyberrys** [OHDSI/Athena#309]
Vocabulary cannot be downloaded, it is pending, and it does not come through e-mail

What should I do?

**Comment by mik-ohdsi** [comment]
apologies @abbyberrys - we are experiencing some issues with Athena sending out emails as many email providers currently consider it spam. We are working on a fix. However, did you check in your "history page" if there is a link for your vocabulary bundle? If so, you can conveniently download it from there. That link stays as long as the bundle has not been outdated and deleted. After initiating the download check the history page maybe an hour later and it should be there. If that is not the case, we will investigate further.

**Comment by mik-ohdsi** [comment]
@abbyberrys  - we think we have fixed the email issues with Athena. Can you check if it works for you now and close the issue if it does?
Thanks - mik

**Comment by mik-ohdsi** [comment]
assuming @abbyberrys  issue has been fixed with the current release of Athena
