### ISSUE TITLE
"CLICK HERE TO LOGIN" button leads to an error page

### ISSUE THREAD

**Issue by jrialland** [OHDSI/Athena#315]
Observed behavior:
--------------------------

When I click on the button "CLICK HERE TO LOGIN" on the page https://athena.ohdsi.org/auth/login,  a popup window opens with an error page : 

 ![image](https://user-images.githubusercontent.com/492066/187720957-4e07672a-2a30-48e3-a624-5244d188c3a6.png)

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Aug 31 15:41:20 UTC 2022
There was an unexpected error (type=Internal Server Error, status=500)."
```

I had previously completed the registration and confirmed my email by clicking on the link i have received.

Expected : 
--------------

being able to login by typing my email and password

**Comment by konstjar** [comment]
Thank you for reporting this. The issue was resolved.
