### ISSUE TITLE
Missing Athena Vocabulary -HGNC (Human Gene Nomenclature (European Bioinformatics Institute)

### ISSUE THREAD

**Issue by KJDonovan-RS21** [OHDSI/Athena#317]
The vocabulary HGNC (Human Gene Nomenclature (European Bioinformatics Institute) is listed on the Athena vocabulary site https://athena.ohdsi.org/vocabulary/list as an optional download, but when selected no vocabulary or concepts are downloaded.  Is this vocabulary available from Athena or should I download it elsewhere and stand up as a custom vocabulary?

**Comment by mik-ohdsi** [comment]
This is a duplicate to this [issue](https://github.com/OHDSI/Vocabulary-v5.0/issues/677).
