### ISSUE TITLE
CPt4.jar does not update CPT codes

### ISSUE THREAD

**Issue by merlina2** [OHDSI/Athena#322]
I'm unable to get the CPT4 /concept update jar to function as expected. 

 I have had this work in the past, but I just recently updated my vocabulary to the most recent  version and  I'm unable to get it two work with my most recent download:

Vocabulary version:

V5.0 31-OCT-22

INFO ] 2022-12-02 17:13:03.048 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  16632/16632
[INFO ] 2022-12-02 17:54:18.927 [main] ConceptService - Not processed cpt4 concepts: 12532. See logs/not-processed-concepts-12-02-2022-17-13-02.out, file. You can find more information about errors in the logs/logfile.log file
[logfile.log](https://github.com/OHDSI/Athena/files/10155763/logfile.log)
[not processed concepts.log](https://github.com/OHDSI/Athena/files/10155764/not.processed.concepts.log)

**Comment by mik-ohdsi** [comment]
Hi @merlina2 - in the log we see a good part of the codes being processed in the beginning, then lots of fails with some intermittent successes. Is there a possibility that you had a sketchy internet connection and the calls to the UMLS API timed out? 
Can you try again while on a fast and reliable line? If that leads to the same result, please let us know and we will investigate more!

**Comment by jacob-kydd** [comment]
Hi @mik-ohdsi,
I saw the same issue come up when running the cpt4.jar this week. In my case, the codes were processed correctly at the start, but when I checked the logs, I found that 12,772 codes failed to process. 


    [INFO ] 2022-12-07 12:37:23.911 [pool-2-thread-15] ConceptUpdater - Update status:FAIL. The code value for id 2213276 is []
    [INFO ] 2022-12-07 12:37:24.020 [main] ConceptService - Not processed cpt4 concepts: 12772. See logs/not-processed-concepts-12-07-2022-12-05-41.out, file. You can find more information about errors in the logs/logfile.log file

**Comment by mik-ohdsi** [comment]
Hi @merlina2 and @jacob-kydd  -  thanks, will test locally!

**Comment by mik-ohdsi** [comment]
okay. I see the same behavior and it is also excruciatingly slow... My suspicion is that the UMLS API is a little stretched. One test will be to start the run again and if it starts filling in the blanks (the logic does that: if it picks up unfilled ones, if you start it again, it tries to fill them), but probably not all at once... we have a confirmation that the API is the "culprit" (or our handling of slow responses).

**Comment by mik-ohdsi** [comment]
so, @merlina2 and @jacob-kydd, my tests kind of confirm that this supposedly is on the UMLS API side... This however makes troubleshooting really difficult. I would not know what is the best way to figure out what exactly happens...

After the first run, I had a similar number of failed entries as you did. In the second run, it showed again the same number and I was already puzzled. In the third run, it catched up and got some more concepts processed. I am now running it again (and again... if necessary), until I have all concepts processed.

```
C:\Users\[myUser]\Documents\vocabularies\downloads\vocabulary_download_v5_20221207_cpt4test>cpt.bat [myAPIKey]
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2022-12-09 11:37:35.067 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  16632/16632
[INFO ] 2022-12-09 13:29:37.434 [main] ConceptService - Not processed cpt4 concepts: **12573**. See logs/not-processed-concepts-12-09-2022-11-37-33.out, file. You can find more information about errors in the logs/logfile.log file

C:\Users\[myUser]\Documents\vocabularies\downloads\vocabulary_download_v5_20221207_cpt4test>cpt.bat [myAPIKey]
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2022-12-09 13:31:35.328 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  12573/12573
[INFO ] 2022-12-09 15:05:17.555 [main] ConceptService - Not processed cpt4 concepts: **12573**. See logs/not-processed-concepts-12-09-2022-13-31-33.out, file. You can find more information about errors in the logs/logfile.log file

C:\Users\[myUser]\Documents\vocabularies\downloads\vocabulary_download_v5_20221207_cpt4test>cpt.bat [myAPIKey]
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2022-12-09 17:58:11.124 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  12573/12573
[INFO ] 2022-12-09 18:35:38.744 [main] ConceptService - Not processed cpt4 concepts: **4598**. See logs/not-processed-concepts-12-09-2022-17-58-09.out, file. You can find more information about errors in the logs/logfile.log file
```

This clearly is a change to the behavior until recently and I cannot explain it.

One possible approach is maybe to slow down the API calls as UMLS points out in their [terms of services](https://documentation.uts.nlm.nih.gov/terms-of-service.html) that performing more than 20 calls per second and IP Address may be sanctioned. Maybe this is being enforced now. Might be interesting for you @alex-odysseus

**Comment by cgreich** [comment]
We may want to improve the tool, so it checks itself what it has done and what it has not, and retries the missing ones. Only if it fails, say, 3 times it gives up and gives a proper error message.

**Comment by jacob-kydd** [comment]
@mik-ohdsi Thanks for looking into this! It would be great to restore the previous behavior and be able to run the tool once to update all of the concepts. Even if this makes it run longer.
Also, would it make sense to throw an error if concept names fail to update? Currently, it's an [INFO] event. This would help with my workflow, and prevent files with empty concept names from being used.

**Comment by mik-ohdsi** [comment]
I have received notice from UMLS now that they have indeed made changes to their API and that it runs on certain [metrics](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html) that we would have to adopt the CPT4.jar logic to. Please bear with us for a short while we put this on the board.

**Comment by jacob-kydd** [comment]
@mik-ohdsi I recently tried rerunning cpt4.jar and it seems to be stuck on 277 concepts not updated. The same 277 concepts are not updated even if rerun it multiple times now. I attached the log file for you to review.

[logfile.log](https://github.com/OHDSI/Athena/files/10493118/logfile.log)
[not-processed-concepts-01-24-2023-13-46-08.log](https://github.com/OHDSI/Athena/files/10493120/not-processed-concepts-01-24-2023-13-46-08.log)

**Comment by alex-odysseus** [comment]
Jacob, do you use the latest version, there were multiple released in the latest days to have a workaround for the UMLS API limitation? @jacob-kydd

**Comment by jacob-kydd** [comment]
@alex-odysseus I'm getting better results with the latest version! It's stuck on only 9 concepts not processed now:

[INFO ] 2023-01-27 15:14:14.014 [main] ConceptService - Writing updated data to CONCEPT.csv
[INFO ] 2023-01-27 15:14:25.040 [pool-2-thread-4] ConceptUpdater - Update status:FAIL. The code value for id 733017 is []
[INFO ] 2023-01-27 15:14:25.095 [pool-2-thread-5] ConceptUpdater - Update status:FAIL. The code value for id 733016 is []
[INFO ] 2023-01-27 15:14:25.097 [pool-2-thread-8] ConceptUpdater - Update status:FAIL. The code value for id 733020 is []
[INFO ] 2023-01-27 15:14:25.098 [pool-2-thread-3] ConceptUpdater - Update status:FAIL. The code value for id 733015 is []
[INFO ] 2023-01-27 15:14:25.101 [pool-2-thread-7] ConceptUpdater - Update status:FAIL. The code value for id 733018 is []
[INFO ] 2023-01-27 15:14:25.101 [pool-2-thread-2] ConceptUpdater - Update status:FAIL. The code value for id 733010 is []
[INFO ] 2023-01-27 15:14:25.102 [pool-2-thread-9] ConceptUpdater - Update status:FAIL. The code value for id 733021 is []
[INFO ] 2023-01-27 15:14:25.102 [pool-2-thread-6] ConceptUpdater - Update status:FAIL. The code value for id 733019 is []
[INFO ] 2023-01-27 15:14:25.309 [pool-2-thread-1] ConceptUpdater - Update status:FAIL. The code value for id 733009 is []
[INFO ] 2023-01-27 15:14:25.323 [main] ConceptService - Not processed cpt4 concepts: 9. See logs/not-processed-concepts-01-27-2023-15-14-13.out, file. You can find more information about errors in the logs/logfile.log file

**Comment by mik-ohdsi** [comment]
Hi @jacob-kydd - please look into this [issue](https://github.com/OHDSI/Vocabulary-v5.0/issues/752). It should be working now. Please close this issue if it worked for you!
Thanks!

**Comment by mik-ohdsi** [comment]
I guess we can close this issue after others have run the newer version successfully.

**Comment by jacob-kydd** [comment]
@mik-ohdsi It did work for me the most recent time I ran it, thanks for the help!
