### ISSUE TITLE
Can not download from Athena

### ISSUE THREAD

**Issue by mjholla30107** [OHDSI/Athena#324]
Trying to download concept ids for LOINC lab test. If I choose any other class OTHER than "Lab Test" the download is fine. If I select "Lab Test" I get a "WhiteLabel" error. I think that is a spring JS error but not sure.

**Comment by mik-ohdsi** [comment]
Hi @mjholla30107 , 
can you go into some more detail where and how you tried to download Concept IDs? From the Search / Browse dialogue (I guess this one) or the actual vocabulary download page? The Search dialogue, I guess... The download there is meant for small sets of concepts of course, only. Please describe all the steps in detail to help reproducing the behavior. Thanks!

**Comment by mjholla30107** [comment]
Good morning Michael,
   Here are the steps to recreate the issue


  1.  Naviage to https://athena.ohdsi.org/search-terms/start
  2.  Click Measurements under Explore
  3.  Add Standard for concept
  4.  Add Lab Test for Class
  5.  Add LOINC for Vocab
  6.  Add Valid for Validity

Then add "LOINC" in the search terms to enable the download button
***@***.***

SO that my search looks like this
***@***.***

Athena returns 56000 + results. I then try to click the download button and this is the message I get

***@***.***

If I choose Clinical Observation as the class instead of Lab Test as the class, the download works. Also. All other vacabs seems to work just fine. I hope this helps

From: Michael Kallfelz ***@***.***>
Sent: Wednesday, January 11, 2023 10:46 AM
To: OHDSI/Athena ***@***.***>
Cc: Holland, Matthew J. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [OHDSI/Athena] Can not download from Athena (Issue #324)


Hi @mjholla30107<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmjholla30107&data=05%7C01%7Cmjholla%40emory.edu%7C5be761287c8a430af7e308daf3eae3ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638090487447072385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sl%2F3DPXk5HML6r6WVxEPP6Ui%2FJQD8GbmQ9%2F4npJyVO0%3D&reserved=0> ,
can you go into some more detail where and how you tried to download Concept IDs? From the Search / Browse dialogue (I guess this one) or the actual vocabulary download page? The Search dialogue, I guess... The download there is meant for small sets of concepts of course, only. Please describe all the steps in detail to help reproducing the behavior. Thanks!

-

**Comment by mik-ohdsi** [comment]
Okay, @mjholla30107 , so this is probably the [Athena query](https://athena.ohdsi.org/search-terms/terms?domain=Measurement&vocabulary=LOINC&standardConcept=Standard&conceptClass=Lab+Test&page=1&pageSize=15&query=%2A%3F%3F%2A&boosts) that you are trying to download from.
As I said earlier, this download function is only meant for smaller sets of concepts. If you choose Clinical Observations it is only 8809 as opposed to 56103 entries for Lab Test. We could maybe implement a better error message or disable the download button once a certain threshold is exceeded. As a rule of thumb, do not use this download function for results more than a couple hundred. Get an Athena user, go to the download page and download only the parts that are interesting for you, then work with the resulting csv files that you get from the download package. 
The Search dialogue in Athena is mostly for browsing the content and drilling down on some details of individual concepts.
Cheers - Mik

**Comment by mjholla30107** [comment]
Thank you Michael

From: Michael Kallfelz ***@***.***>
Sent: Wednesday, January 11, 2023 11:13 AM
To: OHDSI/Athena ***@***.***>
Cc: Holland, Matthew J. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [OHDSI/Athena] Can not download from Athena (Issue #324)


Okay, @mjholla30107<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmjholla30107&data=05%7C01%7Cmjholla%40emory.edu%7C46237d5d1a8f4cd091e308daf3eeb1ac%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638090503751678097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gRt4%2BCK5cE3QvaU6zZk2rPl96gVK6YaMg6B5bzmaJOY%3D&reserved=0> , so this is probably the Athena query<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fathena.ohdsi.org%2Fsearch-terms%2Fterms%3Fdomain%3DMeasurement%26vocabulary%3DLOINC%26standardConcept%3DStandard%26conceptClass%3DLab%2BTest%26page%3D1%26pageSize%3D15%26query%3D%252A%253F%253F%252A%26boosts&data=05%7C01%7Cmjholla%40emory.edu%7C46237d5d1a8f4cd091e308daf3eeb1ac%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638090503751678097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mb1ECWV9qHqs3EeA9prFmALuLPpycgDXjwI6GvdDc18%3D&reserved=0> that you are trying to download from.
As I said earlier, this download function is only meant for smaller sets of concepts. If you choose Clinical Observations it is only 8809 as opposed to 56103 entries for Lab Test. We could maybe implement a better error message or disable the download button once a certain threshold is exceeded. As a rule of thumb, do not use this download function for results more than a couple hundred. Get an Athena user, go to the download page and download only the parts that are interesting for you, then work with the resulting csv files that you get from the download package.
The Search dialogue in Athena is mostly for browsing the content and drilling down on some details of individual concepts.
Cheers - Mik

-
