### ISSUE TITLE
RxNorm Extension Not in Download, 1/11/2023

### ISSUE THREAD

**Issue by liyuanma** [OHDSI/Athena#325]
Dear Athena Team,

I tried to download the RxNorm and RxNorm Extension, but no Extension data were in the download, only RxNorm.

Can you please check?

Thanks,
Larry

**Comment by cgreich** [comment]
Sorry, have to ask: did you click on, and not unclick, it (Vocab 82 in the download selection)?

**Comment by liyuanma** [comment]
Yes, a couple of times.  

Here are some details: there are concepts from RxNorm Extension, but not in sync with Athena (missing records). 

I can see the following in Athena (see screenshot). 
Concept ID 35872576
Concept code OMOP5029006

But this concept is not in the RxNorm Extension Download. 

Thanks,
Larry

![image](https://user-images.githubusercontent.com/40693097/212083276-5abafe0c-2f0c-4171-be36-59b0c44b158c.png)

**Comment by liyuanma** [comment]
Hi Christian,

It turns out to be some mistake with my importing software using the wrong quoting parameters.

The export is fine, and thanks for looking into this.

Best,
Larry
