### ISSUE TITLE
New user registration results in an error 

### ISSUE THREAD

**Issue by ovpatterson** [OHDSI/Athena#328]
I am trying to register as a new user of a web Athena application and after filling out the form I get:

"An error has occurred. Please contact system administrator" 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/15238069/228605149-e4951ade-6abf-4405-892b-294660a7dcb6.png">

**Comment by konstjar** [comment]
I was resolved. Thank you for reporting.
