### ISSUE TITLE
Proxy Error during login 

### ISSUE THREAD

**Issue by lumosan** [OHDSI/Athena#329]
Hello,

I can’t login from athena.ohdsi.org/auth/login due to a Proxy Error. I get the same error from several browsers (Google Chrome, Microsoft Edge, Firefox, Safari).

```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GEI/cas/idp/profile/SAMI2/Redirect/SSO.
Reason: Error reading from remote server
```

**Comment by konstjar** [comment]
Thank you for reporting. It was resolved
