### ISSUE TITLE
Cant register for Athena

### ISSUE THREAD

**Issue by sloboy** [OHDSI/Athena#335]
I am trying to register on https://athena.ohdsi.org/auth/register

The Professional Type dropdown is mandatory, but the list is not populated and typing is not enabled.  It won't let me past this step to create an account.

Thanks,
Derek

**Comment by konstjar** [comment]
Probably it was temporary outage. I checked it's working now.

**Comment by sloboy** [comment]
I was able to register now, thank you for the attention!
