### ISSUE TITLE
Athena search results downloading in unusable format (no delimiters)

### ISSUE THREAD

**Issue by rmcarnahan** [OHDSI/Athena#336]
Hello. I'm downloading results of an Athena search and getting a text file with no delimiters. There are spaces between column items, but there are also spaces within some of the column values, so it seems basically impossible to use the results. Would it be possible to change this to a comma or pipe delimited file, or am I missing something? Thanks.

**Comment by MaximMoinat** [comment]
The files should be tab-delimited. Could you confirm whether there are really spaces, or actually tabs?

**Comment by konstjar** [comment]
The files have tab delimiter. It's not the spaces.

**Comment by rmcarnahan** [comment]
Hello. I’m pretty sure that’s not what I’m getting. When I open this downloaded result in Notepad the rows do not start at a consistent column position. There are tab delimiters, but they are randomly placed and do not appear distinguishable from other spaces within fields.

Thanks,

Ryan

From: Konstantin Yaroshovets ***@***.***>
Sent: Monday, July 17, 2023 1:15 PM
To: OHDSI/Athena ***@***.***>
Cc: Carnahan, Ryan M ***@***.***>; Author ***@***.***>
Subject: [External] Re: [OHDSI/Athena] Athena search results downloading in unusable format (no delimiters) (Issue #336)


The files have tab delimiter. It's not the spaces.

**Comment by MaximMoinat** [comment]
Tabs will not align the columns. What you are describing is expected in a normal Athena vocabulary file.

**Comment by rmcarnahan** [comment]
Thanks. That would bring this back to my original suggestion to add useful delimiters. I’m not aware of a method to read this file into a usable table without different delimiters. The spaces between values that are supposed to be delimiters do not appear different than spaces that can be found within individual values (cells), and there is no consistent start position for values. So how would one identify where each cell begins and ends?

I was able to create a workaround by copying and pasting the web table using Firefox, something that didn’t work with two other browsers, but that’s not an ideal solution. A file with comma or pipe delimiters would be better.

Ryan

From: Maxim Moinat ***@***.***>
Sent: Monday, July 17, 2023 1:27 PM
To: OHDSI/Athena ***@***.***>
Cc: Carnahan, Ryan M ***@***.***>; Author ***@***.***>
Subject: [External] Re: [OHDSI/Athena] Athena search results downloading in unusable format (no delimiters) (Issue #336)


Tabs will not align the columns. What you are describing is expected in a normal Athena vocabulary file.

**Comment by MaximMoinat** [comment]
There are many methods of reading in a tab delimited file. Please search for 'tsv' and the programming language you are using.
