### ISSUE TITLE
CAS 500 error on sign in 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/Athena#337]
After clicking "Sign in" button...
![image](https://github.com/OHDSI/Athena/assets/13469976/823209a9-e3b6-4fe1-899f-574acaadb032)

```
Error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

View Details: null
```

Shot in the dark here but did a cert expire?

**Comment by konstjar** [comment]
Thank you for reporting. The problem was resolved.
