### ISSUE TITLE
Unable to download search results

### ISSUE THREAD

**Issue by jojejoby** [OHDSI/Athena#345]
Error with downloading a subset with the Search functionality

https://athena.ohdsi.org/search-terms/terms?domain=Geography&standardConcept=Standard&page=1&pageSize=500&query=Geography&boosts

Error Message
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Oct 06 12:04:05 UTC 2023
There was an unexpected error (type=Bad Request, status=400).
```

**Comment by konstjar** [comment]
Probably it was temporary issue. Please try again. The services works correct.
