### ISSUE TITLE
"timer EULA required" 

### ISSUE THREAD

**Issue by DSLituiev** [OHDSI/Athena#347]
I have sign saying "⏱️ EULA required" at MedDRA, which is not clickable and has been there for a while.
Is there anything I can do about it? 
Is it stuck (several months already passed)?

**Comment by konstjar** [comment]
@Alexdavv Can you please check

**Comment by lmcewen-helix** [comment]
Same issue here, however, I just recently requested access. I was expecting an email to show proof of the MedDRA MSSO license as described [here](https://forums.ohdsi.org/t/athena-medra-eula/3645/4), but I haven't received anything yet.

**Comment by katiasantaca** [comment]
Good morning,
I have sign saying "⏱️ EULA required" at MedDRA two days ago.
I was expecting an email to show proof of the MedDRA MSSO license as described [here](https://forums.ohdsi.org/t/athena-medra-eula/3645/4), but I haven't received anything yet.
Thanks

**Comment by Alexdavv** [comment]
> I have sign saying "⏱️ EULA required" at MedDRA, which is not clickable and has been there for a while. Is there anything I can do about it? Is it stuck (several months already passed)?

Hi @DSLituiev! The request from April we maybe missed, but the never one was fulfilled in Nov so you should have access.

> Same issue here, however, I just recently requested access. I was expecting an email to show proof of the MedDRA MSSO license as described [here](https://forums.ohdsi.org/t/athena-medra-eula/3645/4), but I haven't received anything yet.



> Good morning,
> I have sign saying "⏱️ EULA required" at MedDRA two days ago.
> I was expecting an email to show proof of the MedDRA MSSO license as described [here](https://forums.ohdsi.org/t/athena-medra-eula/3645/4), but I haven't received anything yet.
> Thanks

Friends, please be patient and allow some time. All the requests are being handled manually, and we have plenty of them.
Usually, we respond within a week, but sometimes it takes longer.
I added this information [here](https://github.com/OHDSI/Vocabulary-v5.0/wiki/General-Structure,-Download-and-Use#availability-license-download).
