### ISSUE TITLE
Athena can't see any data

### ISSUE THREAD

**Issue by gslin1224** [OHDSI/Athena#354]
Hello guys:
I Building local Athena,
I builded postgreSQL and solr on docker

<img width="1470" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/886264ea-a760-46d6-b72c-992542b9ddce">

<img width="1467" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/20043b88-1426-4355-ba19-a70e66d07d6a">
Athena connected to Athena_cdm_v5 when I java Athena.jar.

but I open the web, can't see any data on web.
<img width="1457" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/66d53f6a-25f8-455f-ab5c-6c2a7db5a501">

Can anyone help me?,thank a lot.

**Comment by konstjar** [comment]
Athena reads most of the data from Solr. Probably there is a problem with Solr connection or your Solr cores.

**Comment by gslin1224** [comment]
> Athena reads most of the data from Solr. Probably there is a problem with Solr connection or your Solr cores.

thank your reply.

but I certain solr have connected to Athena too.

<img width="901" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/3218afcc-26a9-4b7e-a813-5e66c4f05349">

maybe I have lost some step?

when I first open solr admin see it doesn't create schema

so I create them

<img width="722" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/c7b5d06a-9433-475a-ac25-955c961a1787">

**Comment by gslin1224** [comment]
> Athena reads most of the data from Solr. Probably there is a problem with Solr connection or your Solr cores.

and I solrconfig is default

solr dataimport display:
<img width="1016" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/f6578419-c466-47a1-baf2-4b032c4af091">

**Comment by gslin1224** [comment]
<img width="593" alt="image" src="https://github.com/OHDSI/Athena/assets/151395340/d2dcaceb-82bb-4ac7-99a1-48ac7bafc5cd">

**Comment by gslin1224** [comment]
I put all Athena/solr data to my solr container after,
can display solr admin dataimport now,
but still doesn't have any data.
how dataimport?
or I miss what step?
thank a lot

**Comment by gslin1224** [comment]
> Athena reads most of the data from Solr. Probably there is a problem with Solr connection or your Solr cores.

I dataimport after, web can display data now.

thank your advice
