### ISSUE TITLE
Unable to download vocabularies

### ISSUE THREAD

**Issue by mashto786** [OHDSI/Athena#384]
Tried to redownload vocabularies which failed.  Attempting to redownload fresh raised an exception when attempting to download
<img width="837" alt="image" src="https://github.com/OHDSI/Athena/assets/75364920/cc1fe5af-5498-4a7a-abf6-66aebba1ef46">

**Comment by chrisroederucdenver** [comment]
I'm seeing this too.

**Comment by konstjar** [comment]
The problem was resolved. Thank you for logging it.
