### ISSUE TITLE
Error when downloading vocabularies

### ISSUE THREAD

**Issue by lizumberfield** [OHDSI/Athena#387]
When attempting to download vocabularies the following error message appears:
"result":null,"errorMessage":"org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement","errorCode":4,"validatorErrors":{}}

**Comment by konstjar** [comment]
Thank you for reporting this. The issue was resolved. Please try to download again
