### ISSUE TITLE
JDBC error downloading SNOMED vocabulary

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/Athena#390]
I am getting this error when trying to download the SNOMED vocabulary from https://athena.ohdsi.org/vocabulary/list (Version 1.14.0.32.231116.1843; OMOP Vocabulary version: v5.0 29-FEB-24):

```
org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
```

![athena-error](https://github.com/OHDSI/Athena/assets/7384198/89428a5d-cbb8-4bb6-afe1-b9c9cde19e01)

**Comment by konstjar** [comment]
The problem was resolved. Thank you for logging it.
