### ISSUE TITLE
JDBC Exception when downloading vocabularies

### ISSUE THREAD

**Issue by sunnielou** [OHDSI/Athena#395]
Hello, while trying to download a set of vocabularies from ATHENa I get this exception log

> org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement

**Comment by konstjar** [comment]
Thank you for reporting. The issue was resolved. Please try to download again.
