### ISSUE TITLE
API availability for downloading Vocabularies

### ISSUE THREAD

**Issue by isingh41** [OHDSI/Athena#408]
Hi Team,
Its not an issue, but need some details around download of the Vocabularies present on Athena website. Are there some APIs available to fetch the vocabularies instead of downloading the CSV manually and use it further for our purpose. If there are some APIs available, we would be able to automate this process of refreshing vocabulary content every time a new release is available from Athena on the vocabularies. 

Please suggest?

**Comment by konstjar** [comment]
Unfortunately, Athena does not provide APIs for automation due to technical limitations.
