### ISSUE TITLE
https://athena.ohdsi.org vocab download error

### ISSUE THREAD

**Issue by michael-haegg** [OHDSI/Athena#411]
Vocabulary download from https://athena.ohdsi.org/vocabulary/list for any one or several vocabularies throws a java error and does not download.
Error: _org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement_

Website links to this repo for application issues.

**Comment by konstjar** [comment]
The issue was resolved. Please try again

**Comment by konstjar** [comment]
Thanks for reporting. It was resolved.
