### ISSUE TITLE
Cannot download vocabularies - org.hibernate.exception.GenericJDBCException

### ISSUE THREAD

**Issue by cipherome-minkim** [OHDSI/Athena#413]
trying to download a vocabulary and getting this hibernate exception:

```
org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
```

example:
<img width="1402" alt="Screenshot 2024-11-11 at 10 12 58 AM" src="https://github.com/user-attachments/assets/66e471cb-c5f3-4d22-bda5-df0f59b3c080">

**Comment by konstjar** [comment]
Thank you for reporting. The issue was resolved.
