### ISSUE TITLE
Registration for Athena is not secure, uses http and https not available.

### ISSUE THREAD

**Issue by jackwasey** [OHDSI/Athena#45]
https://athena.ohdsi.org/auth/register fails: it redirects to the invalid and insecure URL: http://athena.ohdsi.orgauth/register

In addition, the domain of the certificate when HTTPS is attempted does not match the URL, giving certificate errors.

**Comment by gklebanov** [comment]
will work with @leeevans to add SSL

**Comment by konstjar** [comment]
SSL certificate was configured on Athena server
