### ISSUE TITLE
Athena returns fewer results than expected

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Athena#47]
Original query: 
SELECT c2.concept_id, c2.concept_name, c2.concept_class_id, c2.domain_id, c2.vocabulary_id
FROM concept c2
WHERE c2.vocabulary_id IN ('CPT4', 'SNOMED', 'HCPCS')
AND c2.standard_concept = 'S'
AND c2.domain_id = 'Procedure'
AND c2.domain_id = 'Procedure'
AND lower(c2.concept_name) LIKE '%vasectomy%';
returns 23 rows;

Athena results:
http://athena.ohdsi.org/search-terms/terms?vocabulary=CPT4&vocabulary=SNOMED&vocabulary=HCPCS&standardConcept=Standard&domain=Procedure&page=1&pageSize=15&query=vasectomy
returns 17 rows.

Possible explanation:
All missing results have a bracket before the term:

concept_id | concept_name
-- | --
2109825 | Transurethral electrosurgical resection of prostate, including control of   postoperative bleeding, complete (vasectomy, meatotomy, cystourethroscopy,   urethral calibration and/or dilation, and internal urethrotomy are included)
2109830 | Transurethral resection; residual or regrowth of obstructive prostate   tissue including control of postoperative bleeding, complete (vasectomy,   meatotomy, cystourethroscopy, urethral calibration and/or dilation, and   internal urethrotomy are included)
42627874 | Transurethral waterjet ablation of prostate, including control of   post-operative bleeding, including ultrasound guidance, complete (vasectomy,   meatotomy, cystourethroscopy, urethral calibration and/or dilation, and   internal urethrotomy are included when p
2109832 | Laser coagulation of prostate, including control of postoperative   bleeding, complete (vasectomy, meatotomy, cystourethroscopy, urethral   calibration and/or dilation, and internal urethrotomy are included if   performed)
2109834 | Laser enucleation of the prostate with morcellation, including control of   postoperative bleeding, complete (vasectomy, meatotomy, cystourethroscopy,   urethral calibration and/or dilation, internal urethrotomy and transurethral   resection of prostate are inc
2109833 | Laser vaporization of prostate, including control of postoperative   bleeding, complete (vasectomy, meatotomy, cystourethroscopy, urethral   calibration and/or dilation, internal urethrotomy and transurethral resection   of prostate are included if performed)

**Comment by pavgra** [comment]
Covered by https://github.com/OHDSI/Athena/issues/60
