### ISSUE TITLE
CONCEPT.csv damaged by UMLS API issues

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Athena#52]
When trying to connect to UMLS to get the CPT codes (via the provided instructions), I encountered this error:

> Update failed. UMLS web-API crashed. Error getting a ticket granting ticket: null

Which effectively causes the CONCEPT.CSV file to become empty. This is probably due to UMLS authentication not working (at this precise moment). But the CONCEPT.CSV file should not be zapped by this error.

**Comment by vojtechhuser** [comment]
in my case I also saw the import to be super slow and problematic

**Comment by olga-ganina** [comment]
Hello @jmbanda , @vojtechhuser  , apologize for the delay in response, we have released the new Athena version with CPT4 updates, could you please let me know if you still have issues.

**Comment by mik-ohdsi** [comment]
I consider this issue closed for a while already.
