### ISSUE TITLE
Notifications on vocabulary updates + CDM Version

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#53]
When I download a new vocabulary, I have the option to ask for notifications. Until now I have never received these. Is this functionality working?

Furthermore, the latest CDM version you can select is old. Suggest to update this even if the vocabulary tables have not changed. I think there were changes..

<img width="744" alt="image" src="https://user-images.githubusercontent.com/7252105/53302040-5cfff080-385a-11e9-81ab-68078f06605d.png">

**Comment by vojtechhuser** [comment]
+1 - please explain or fix

**Comment by PRijnbeek** [comment]
Any updates on this?

**Comment by gklebanov** [comment]
@PRijnbeek / @vojtechhuser - apologies for missing this question. 

Notifications - unfortunately, we just collect the subscription flag at this point but the notification feature has not been implemented. It is in the backlog but at this point it is not the highest priority (plus need to get a stable ATLAS 2.7.1 and ARACHNE 1.14 first)

Versions - yeah, should fix it. Just probably list it as "4.x" and "5.x" - this should be a relatively small and quick fix and I will ask the team to get it in place in the next few days.

**Comment by acumarav** [comment]
Hello @gklebanov 
Taking into account that all the vocabularies are released as on solid pack I have one question:
What this subscription means? Should user get notification at each next vocabulary release or only in case change was made in one of the vocabularies which user are downloading?
(First option is obviously simpler)

**Comment by acumarav** [comment]
I am going to implement notifications in the following way:
1. When a user creates subscription - system stores actual vocabulary version
2. Add nightly job which compares versions and sends out an email if versions do not match. (the system should update the actualVersion value after the email so that it would not occur the next day)

3. One email should contains all the subscribed updates

**Comment by olga-ganina** [comment]
Implemented and available at http://athena.ohdsi.org
