### ISSUE TITLE
Copyright Ends in 2017

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Athena#59]
Silly - but I noticed it so figured I'd log it.

Dates highlighted are 2015-2017, I'm assuming this is supposed to go to 2019.

![image](https://user-images.githubusercontent.com/6305439/55020019-605ad900-4fcc-11e9-975f-42ee95f7bfd4.png)

**Comment by olga-ganina** [comment]
Implemented and available at http://athena.ohdsi.org
