### ISSUE TITLE
CPT4 instructions in Athena email

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Athena#6]
I receive this email text:

"Important: All vocabularies are fully represented in the downloaded files with the exception of CPT-4: OHDSI does not have a distribution license to ship CPT-4 codes together with the descriptions. Therefore, we provide you with a utility that downloads the descriptions separately and merges them together with everything else. After unpacking, simply open a command line in the directory you unpacked all the files into and run "java -jar cpt4.jar""

However, this should be "java -jar cpt4.jar 5" in the case of CDM version 5. You see that when you run without the version so not a big issue, but it is a bit counter intuitive to ask for a CDM version 5 vocab in the ATHENA website and then need to specify the version. Would be better if it would default to the cdm version I selected in Athena (add a setting file?).

**Comment by cgreich** [comment]
Peter:

You are totally correct. Will fix the instruction.

The automatic version: I agree, it's in the backlog. Not very high up, though. :(

**Comment by olga-ganina** [comment]
Is already implemented and available on production.
