### ISSUE TITLE
Database exception, not able to download vocabularies

### ISSUE THREAD

**Issue by CSberger** [OHDSI/Athena#61]
Database exception, not able to download vocabularies

I've been blocked by this issue most of the day.  When I try and download the vocabulary csvs, I'm given an exception message.

![athena_bug](https://user-images.githubusercontent.com/1278167/57828206-89dbe980-775f-11e9-964b-81be7007e268.gif)
<img width="1487" alt="Screen Shot 2019-05-15 at 10 18 21 PM" src="https://user-images.githubusercontent.com/1278167/57828215-92ccbb00-775f-11e9-956b-05ddffed1932.png">

**Comment by konstjar** [comment]
The problem was resolved. Thank you for reporting this
