### ISSUE TITLE
Add HemOnc license agreement into License popup

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Athena#64]
Per @cgreich :

Need to add HemOnc license agreement into License popup (which appears the first time a user enters website). It should come after the Snomed's license:
```
SNOMED INTERNATIONAL SNOMED CT LICENSE AGREEMENT
...text...

HemOnc license agreement
...text...
```

License text:
[HemOnc click-thru license_PY 6-11.docx](https://github.com/OHDSI/Athena/files/3290976/HemOnc.click-thru.license_PY.6-11.docx)

**Comment by olga-ganina** [comment]
Implemented and available at http://athena.ohdsi.org
