### ISSUE TITLE
Be able to tag a collection of vocabularies and share it with other collaborators

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Athena#65]
The new feature request (idea) is to allow a user tag a collection of vocabularies and share this tag/collection with other collaborators so that multiple institutions would be able to download the same  vocabularies.

@Karthik Natarajan

**Comment by dimshitc** [comment]
Actually there is a problem with versioning.
We don't store previous versions of the vocabulary.
Once the new vocabulary released (even if we changed only one concept there), the previous version becomes unavailable.

And not directly related, but, I think, it's nice - why not to show the vocabulary version (release date) on the "download page"?

**Comment by acumarav** [comment]
I am working on it, just a question probably to the @gklebanov  or other - what does it mean "share it with other collaborators" - should collection create define the list of persons to share with or shared set become available to the every authenticated user?

**Comment by gklebanov** [comment]
@cukarthik - Karthik, please propose an idea on how to specify the list with whom the bundle should be shared? Keeping in mind that some of them might not yet have an ATHENA account

**Comment by acumarav** [comment]
I think we cannot show list of users from the database to pick from, so the only options are - emails or share to everyone - which mean that app will have list of publicly visible bundles to download.

So functionality can looks like:
We reuse download_bundles
Owner of the bundle can set tags, description and share/unshare it.
All shared bundles visible to all authenticated users and available to download
bundle status transitions stays the same

**Comment by olga-ganina** [comment]
Implemented and available at http://athena.ohdsi.org
