### ISSUE TITLE
Process non-standard ASCII characters correctly

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Athena#86]
For example, the name of user mbarbe@gmail.com is "Barbé", not "Barb��".

**Comment by acumarav** [comment]
The issue is caused by the CAS component and can be fixed without Athena release

**Comment by acumarav** [comment]
Test: 
https://drive.google.com/file/d/1nWB_zbYOM2o8XNfMsnuS9cQrz8m_ruj1/view?usp=sharing
