### ISSUE TITLE
Quarterly report for proprietary dictionaries

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Athena#87]
We need the ability to pull a report: Each user, and all the downloaded vocabs. At least all the ones with a license requirement, including SNOMED. By time span, default the last quarter.

**Comment by cgreich** [comment]
More detail:

1. Query page with the following criteria:
- time period (default: Last quarter)
- keyword search for names and institutions
- vocabularies

2. Download in Excel in some not completely ugly format (which I otherwise need to fix each time).

**Comment by acumarav** [comment]
Test: https://drive.google.com/file/d/1iNKw5Fq2NcwrX-C3nJRzbr5bFEUmNIUK/view?usp=sharing
