### ISSUE TITLE
Unable to register on Athena website

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Athena#9]
I'm trying to register on the [Athena website](https://athena.odysseusinc.com/auth/register), but when I click REGISTER nothing happens. This is probably because the Professional Type dropdown box isn't working, so that field is empty (but I get no message).

Using Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by mpozhidaeva** [comment]
Hello, @schuemie - thank you for your message, please try to choose professional type and registrate again

**Comment by schuemie** [comment]
Thanks! The drop box now works, and I've just registered
